// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterTools(arg1) {
  return window['go']['mcp']['AvnacMCP']['RegisterTools'](arg1);
}

export function Start(arg1) {
  return window['go']['mcp']['AvnacMCP']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['mcp']['AvnacMCP']['Stop'](arg1);
}

export function SubmitResponse(arg1, arg2) {
  return window['go']['mcp']['AvnacMCP']['SubmitResponse'](arg1, arg2);
}
